name: tech-news-instance

services:
    db-instance:
        network_mode: host
        ports:
            - 127.0.0.1:1433:1433
        environment:
            - MSSQL_PID=Express
            - MSSQL_SA_PASSWORD="abcD_123"
            - ACCEPT_EULA="Y"
        healthcheck:
            test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$$MSSQL_SA_PASSWORD" -Q "SELECT 1" -b -o /dev/null
            interval: 10s
            timeout: 10s
            retries: 60
        restart: always
        image: anhvlt/the-tech-news:db-latest

    web-instance:
        ports:
            - 127.0.0.1:8080:8080
        depends_on:
            db-instance:
                condition: service_healthy
        restart: always
        image: anhvlt/the-tech-news:web-latest
