name: Build Web App to Docker Container
permissions:
  contents: read
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 1
jobs:
  build-tomcat:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2
      - name: Build Web & Validating before pushing to Docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./.docker/dockerfile-web
          push: false

      - name: Build MS SQL & Validating before pushing to Docker
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./.docker/dockerfile-db
          push: false

      - name: Log in to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
        if: github.ref == 'refs/heads/master'
        
      - name: Build Web & Push to Docker Hub
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./.docker/dockerfile-web
          push: true
          tags: 'anhvlt/the-tech-news:web-latest'
        if: github.ref == 'refs/heads/master'

      - name: Build MS SQL & Push to Docker Hub
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./.docker/dockerfile-db
          push: true
          tags: 'anhvlt/the-tech-news:db-latest'
        if: github.ref == 'refs/heads/master'
